version: '3'

services:
  app:
    container_name: platia-workflow
    image: node:lts-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      PORT: 3000 # HOST PORT
    ports:
      - 4000:3000 # [CONTAINER_PORT]:[HOST_PORT]
    command: npm run start

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
