version: '3'

services:
  app:
    container_name: dataset-store
    image: node:lts-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - minio
    environment:
      NODE_ENV: development
      HOST_PORT: ${HOST_PORT:-3000}
      CONTAINER_PORT: ${CONTAINER_PORT:-3000}
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command: npm run docker-start

  minio:
    image: minio/minio
    volumes:
      - data:/data
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY:-minio}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY:-minio123}'
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://minio:9000/minio/health/live']
      interval: 1m30s
      timeout: 20s
      retries: 3

volumes:
  data:
