version: '3'

services:
  app:
    container_name: dataset-store
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - db
      - minio
    environment:
      NODE_ENV: development
      HOST_PORT: ${HOST_PORT:-3000}
      CONTAINER_PORT: ${CONTAINER_PORT:-3000}
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command:
      ["-c", "npm install && /opt/wait-for.sh ${DB_HOST:-mysql}:${DB_PORT:-3306} && knex migrate:latest && npm run docker-start",]
    entrypoint: ["/bin/sh"]

  db:
    container_name: '${DB_HOST:-mysql}'
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-projects}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-supersecret}

  minio:
    container_name: '${MINIO_HOST:-minio}'
    image: minio/minio
    volumes:
      - ./data-minio:/var/lib/minio
    ports:
      - '${MINIO_PORT:-9000}:9000'
    environment:
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY:-secret}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY:-super-secret}'
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://minio:9000/minio/health/live']
      interval: 1m30s
      timeout: 20s
      retries: 3
